// Generated by scripts/build/gen-lua-builtin.py — DO NOT EDIT.
// Source: out/firmware/apps/ (the same .lua the Lua Store serves).
// Seeded built-ins: a downloaded <data>/apps/<id>.lua always wins.
#pragma once

struct LuaBuiltinApp { const char* id; const char* name; const char* ver; const char* src; };

static const char kLuaSrc_monitor[] = R"WADALUA(-- RF Monitor (Lua) — live RSSI/noise chart with a dBm axis, link-margin grade,
-- RX rate, radio parameters and the recently-heard feed. The page scrolls, so
-- the whole feed is reachable on short screens.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local C = ui.colors
local app = {}

local RSSI_MIN, RSSI_MAX = -130, -20
local TYPE = { [1]="ADV", [2]="TXT", [3]="ACK", [4]="GRP", [5]="REQ", [6]="RSP", [7]="PTH", [8]="TRC" }
local TCOL = { [1]=0xA784E0, [2]=0x4F9DF7, [3]=0x53C06B, [4]=0x35C9C9, [5]=0xE8A33D, [6]=0xF2793C }

local W, narrow
local legend, chart, metrics, radio_lbl, feed_hdr, feed_rows = nil, nil, nil, nil, nil, {}
local peak, rx0, t0

local function fmt_ago(ms)
  local s = ms // 1000
  if s < 60 then return s .. "s" end
  if s < 3600 then return (s // 60) .. "m" end
  return (s // 3600) .. "h"
end

local function grade(m)
  if m >= 20 then return "excellent", C.good end
  if m >= 10 then return "good",      C.good end
  if m >= 5  then return "fair",      0xE8A33D end
  if m > 0   then return "weak",      C.bad end
  return "no margin", C.bad
end

local function refresh()
  local st = mesh.stats()
  if st.rssi > peak then peak = st.rssi end
  chart:push(1, math.floor(st.rssi))
  chart:push(2, math.floor(st.noise))

  local mg = st.rssi - st.noise
  local gtxt, gcol = grade(mg)
  local mins = math.max((sys.millis() - t0) / 60000, 1 / 60)

  legend:set(string.format("RSSI %.0f   noise %.0f   peak %.0f dBm", st.rssi, st.noise, peak))
  metrics:set(string.format("margin %.0f dB (%s)   RX ~%.0f/min", mg, gtxt, (st.rx_pkts - rx0) / mins))
  metrics:color(gcol)
  radio_lbl:set(string.format("%.3f MHz  SF%d  BW %.0f   %d rx / %d err / %d drop   duty %d%%",
                              st.freq, st.sf, st.bw, st.rx_pkts, st.rx_err, st.rx_dropped, st.duty_pct))

  local log = mesh.rx_log()
  for i = 1, #feed_rows do
    local r = log[i]
    if r then
      local nm = TYPE[r.type] or ("t" .. r.type)
      if narrow then
        feed_rows[i]:set(string.format("%-4s %-3s %4d %5.1f %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "dir" or (r.hops .. "h")))
      else
        feed_rows[i]:set(string.format("%-5s %-3s  %4d dBm  %5.1f dB  %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "direct" or (r.hops .. (r.hops == 1 and " hop" or " hops"))))
      end
      feed_rows[i]:color(TCOL[r.type] or C.text)
    else
      feed_rows[i]:set(i == 1 and #log == 0 and "listening - nothing heard yet" or "")
      feed_rows[i]:color(C.sub)
    end
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  ui.scroll(true)                      -- the feed runs past the screen; let it scroll
  local LH12 = ui.text_h(12)           -- real line heights, no guessing
  local st = mesh.stats()
  rx0, t0, peak = st.rx_pkts, sys.millis(), st.rssi

  local y = 4
  legend = ui.label("", 4, y, 12, C.accent); legend:width(w - 10); y = y + LH12 + 4

  local AX, ch_h = 38, narrow and 62 or 76
  chart = ui.chart(w - AX - 8, ch_h, 72, C.accent, C.sub)
  chart:pos(AX, y)
  chart:range(RSSI_MIN, RSSI_MAX)
  chart:axis(3, AX)
  y = y + ch_h + 6

  metrics = ui.label("", 4, y, 12, C.text); metrics:width(w - 10)
  y = y + LH12 * (narrow and 2 or 1) + 3
  radio_lbl = ui.label("", 4, y, 12, C.sub); radio_lbl:width(w - 10)
  y = y + LH12 * (narrow and 3 or 2) + 5

  feed_hdr = ui.label(narrow and "recently heard" or "recently heard (newest first)", 4, y, 12, C.sub)
  feed_hdr:width(w - 10)
  y = y + LH12 + 3
  for i = 1, 16 do                     -- scrolling means we can show the whole ring
    feed_rows[i] = ui.label("", 4, y, 12, C.text)
    feed_rows[i]:width(w - 10)
    y = y + LH12 + 2
  end

  refresh()
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_airtime[] = R"WADALUA(-- Airtime (Lua) — channel utilization over time: live + average bars with a %
-- axis, rx/tx air split, duty ceiling, tx budget and packet counters.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local C = ui.colors
local app = {}

local W, narrow
local head, sub, legend, detail, chart
local base, t0, last
local peak_pct = 0

local function restart_window()
  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  peak_pct = 0
  chart:fill(1, 0)
  chart:fill(2, 0)
  head:set("sampling...")
  head:color(C.accent)
  sys.toast("window restarted", 900)
end

local function refresh()
  local st = mesh.stats()
  local now = sys.millis()
  local wall = (now - t0) / 1000
  if wall < 0.5 then return end

  local rx_air, tx_air = st.rx_air_s - base.rx, st.tx_air_s - base.tx
  local avg = math.min(100, (rx_air + tx_air) * 100 / wall)

  local dw = (now - last.ms) / 1000
  local live = 0
  if dw > 0 then
    live = math.min(100, ((st.rx_air_s - last.rx) + (st.tx_air_s - last.tx)) * 100 / dw)
  end
  last = { ms = now, rx = st.rx_air_s, tx = st.tx_air_s }
  if live > peak_pct then peak_pct = live end

  chart:push(1, math.floor(live))
  chart:push(2, math.floor(avg))

  head:set(string.format("channel busy %.1f%%", live))
  head:color(live > 50 and C.bad or live > 20 and 0xE8A33D or C.good)
  sub:set(string.format("avg %.1f%%   peak %.1f%%   over %ds", avg, peak_pct, math.floor(wall)))
  if narrow then
    detail:set(string.format("air rx %ds / tx %ds\nduty %d%%   budget %dms\ntx %d  rx %d  err %d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err))
  else
    detail:set(string.format("air rx %ds / tx %ds   duty %d%%   budget %dms\ntx %d   rx %d   err %d   drop %d   SF%d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err, st.rx_dropped, st.sf))
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  local LH12, LH16 = ui.text_h(12), ui.text_h(16)

  local y = 2
  head = ui.label("sampling...", 4, y, 16, C.accent); head:width(w - 86)
  ui.button("Reset", w - 76, y, 70, 30, function() restart_window() end)   -- top-right
  y = y + LH16 + 4
  sub = ui.label("", 4, y, 12, C.sub); sub:width(w - 10)
  y = y + LH12 + 5

  local AX = 34
  local det_lines = narrow and 3 or 2
  local ch_h = h - y - (det_lines * LH12) - LH12 - 14
  if ch_h < 48 then ch_h = 48 end
  if ch_h > 110 then ch_h = 110 end
  chart = ui.chart(w - AX - 8, ch_h, 60, C.accent, 0x4F9DF7, true)
  chart:pos(AX, y)
  chart:range(0, 100)
  chart:axis(3, AX)
  y = y + ch_h + 4

  legend = ui.label("teal = now   blue = average", 4, y, 12, C.sub); legend:width(w - 10)
  y = y + LH12 + 2
  detail = ui.label("", 4, y, 12, C.text); detail:width(w - 10)

  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_snake[] = R"WADALUA(-- Snake — wada.* reference app. Swipe (or trackball) to steer; eat the red
-- food, don't bite yourself. Tap after a game over to play again.
local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local CELL = 14
local app = {}
local cv, score_lbl
local cols, rows, px_w, px_h
local body, len, dx, dy, ndx, ndy, fx, fy
local score, hiscore, running, over

local function place_food()
  repeat
    fx, fy = sys.random(0, cols - 1), sys.random(0, rows - 1)
    local clash = false
    for i = 1, len do
      if body[i].x == fx and body[i].y == fy then clash = true break end
    end
  until not clash
end

local function reset()
  len, score, over, running = 3, 0, false, false
  dx, dy, ndx, ndy = 1, 0, 1, 0
  body = {}
  local cx, cy = math.floor(cols / 2), math.floor(rows / 2)
  for i = 1, len do body[i] = { x = cx - i + 1, y = cy } end
  place_food()
end

local function scoreline()
  score_lbl:set(string.format("Score %d   Best %d%s", score, hiscore,
                              running and "" or (over and "   -  tap to retry" or "   -  swipe to start")))
end

local function draw()
  cv:fill(0x101418)
  cv:rect(fx * CELL + 2, fy * CELL + 2, CELL - 4, CELL - 4, C.bad, true, 4)
  for i = len, 1, -1 do
    cv:rect(body[i].x * CELL + 1, body[i].y * CELL + 1, CELL - 2, CELL - 2,
            i == 1 and C.accent or C.good, true, 3)
  end
  if over then
    cv:text(math.floor(px_w / 2) - 40, math.floor(px_h / 2) - 10, "GAME OVER", C.text, 16)
  end
end

local function step()
  dx, dy = ndx, ndy
  local head = body[1]
  local nx, ny = head.x + dx, head.y + dy
  if nx < 0 or ny < 0 or nx >= cols or ny >= rows then over = true end
  if not over then
    for i = 1, len - 1 do
      if body[i].x == nx and body[i].y == ny then over = true break end
    end
  end
  if over then
    running = false
    if score > hiscore then
      hiscore = score
      store.set("hiscore", hiscore)
      sys.toast("New high score: " .. hiscore, 1600)
    end
    scoreline()
    draw()
    return
  end
  table.insert(body, 1, { x = nx, y = ny })
  if nx == fx and ny == fy then
    len = len + 1
    score = score + 10
    place_food()
    scoreline()
  else
    body[#body] = nil
  end
  draw()
end

function app.on_open(w, h)
  hiscore = store.get("hiscore", 0)
  cols = math.floor(w / CELL)
  rows = math.floor((h - 26) / CELL)
  px_w, px_h = cols * CELL, rows * CELL
  score_lbl = ui.label("", 4, 4, 14, C.text)
  cv = ui.canvas(px_w, px_h)
  cv:pos(math.floor((w - px_w) / 2), 26)
  reset()
  scoreline()
  draw()
  timer.every(120)
end

function app.on_input(ev)
  if ev.type == "swipe" then
    local d = ev.dir
    if     d == "up"    and dy ~= 1  then ndx, ndy = 0, -1
    elseif d == "down"  and dy ~= -1 then ndx, ndy = 0, 1
    elseif d == "left"  and dx ~= 1  then ndx, ndy = -1, 0
    elseif d == "right" and dx ~= -1 then ndx, ndy = 1, 0
    end
    if not running and not over then running = true; scoreline() end
  elseif ev.type == "down" and over then
    reset()
    scoreline()
    draw()
  end
end

function app.on_tick(dt)
  if running and not over then step() end
end

function app.on_close()
  -- high score is already persisted on set; nothing to tear down (the host
  -- frees every widget and the canvas with the app)
end

return app
)WADALUA";

static const LuaBuiltinApp kLuaBuiltin[] = {
  { "monitor", "RF Monitor", "1.3", kLuaSrc_monitor },
  { "airtime", "Airtime", "1.3", kLuaSrc_airtime },
  { "snake", "Snake", "1.0", kLuaSrc_snake },
};
static const int kLuaBuiltinCount = (int)(sizeof(kLuaBuiltin)/sizeof(kLuaBuiltin[0]));
