// Generated by scripts/build/gen-lua-builtin.py — DO NOT EDIT.
// Source: deploy/apps/ (the same .lua the Lua Store serves).
// Seeded built-ins: a downloaded <data>/apps/<id>.lua always wins.
#pragma once

struct LuaBuiltinApp { const char* id; const char* name; const char* ver; const char* src; };

static const char kLuaSrc_monitor[] = R"WADALUA(


local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local C = ui.colors
local app = {}

local RSSI_MIN, RSSI_MAX = -130, -20
local TYPE = { [1]="ADV", [2]="TXT", [3]="ACK", [4]="GRP", [5]="REQ", [6]="RSP", [7]="PTH", [8]="TRC" }
local TCOL = { [1]=0xA784E0, [2]=0x4F9DF7, [3]=0x53C06B, [4]=0x35C9C9, [5]=0xE8A33D, [6]=0xF2793C }

local W, narrow
local legend, chart, metrics, radio_lbl, feed_hdr, feed_rows = nil, nil, nil, nil, nil, {}
local peak, rx0, t0

local function fmt_ago(ms)
local s = ms // 1000
if s < 60 then return s .. "s" end
if s < 3600 then return (s // 60) .. "m" end
return (s // 3600) .. "h"
end

local function grade(m)
if m >= 20 then return "excellent", C.good end
if m >= 10 then return "good",      C.good end
if m >= 5  then return "fair",      0xE8A33D end
if m > 0   then return "weak",      C.bad end
return "no margin", C.bad
end

local function refresh()
local st = mesh.stats()
if st.rssi > peak then peak = st.rssi end
chart:push(1, math.floor(st.rssi))
chart:push(2, math.floor(st.noise))

local mg = st.rssi - st.noise
local gtxt, gcol = grade(mg)
local mins = math.max((sys.millis() - t0) / 60000, 1 / 60)

legend:set(string.format("RSSI %.0f   noise %.0f   peak %.0f dBm", st.rssi, st.noise, peak))
metrics:set(string.format("margin %.0f dB (%s)   RX ~%.0f/min", mg, gtxt, (st.rx_pkts - rx0) / mins))
metrics:color(gcol)
radio_lbl:set(string.format("%.3f MHz  SF%d  BW %.0f   %d rx / %d err / %d drop   duty %d%%",
st.freq, st.sf, st.bw, st.rx_pkts, st.rx_err, st.rx_dropped, st.duty_pct))

local log = mesh.rx_log()
for i = 1, #feed_rows do
local r = log[i]
if r then
local nm = TYPE[r.type] or ("t" .. r.type)
if narrow then
feed_rows[i]:set(string.format("%-4s %-3s %4d %5.1f %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
r.hops == 0 and "dir" or (r.hops .. "h")))
else
feed_rows[i]:set(string.format("%-5s %-3s  %4d dBm  %5.1f dB  %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
r.hops == 0 and "direct" or (r.hops .. (r.hops == 1 and " hop" or " hops"))))
end
feed_rows[i]:color(TCOL[r.type] or C.text)
else
feed_rows[i]:set(i == 1 and #log == 0 and "listening - nothing heard yet" or "")
feed_rows[i]:color(C.sub)
end
end
end

function app.on_open(w, h)
W, narrow = w, w < 280
ui.scroll(true)
local LH12 = ui.text_h(12)
local st = mesh.stats()
rx0, t0, peak = st.rx_pkts, sys.millis(), st.rssi

local y = 4
legend = ui.label("", 4, y, 12, C.accent); legend:width(w - 10); y = y + LH12 + 4

local AX, ch_h = 38, narrow and 62 or 76
chart = ui.chart(w - AX - 8, ch_h, 72, C.accent, C.sub)
chart:pos(AX, y)
chart:range(RSSI_MIN, RSSI_MAX)
chart:axis(3, AX)
y = y + ch_h + 6

metrics = ui.label("", 4, y, 12, C.text); metrics:width(w - 10)
y = y + LH12 * (narrow and 2 or 1) + 3
radio_lbl = ui.label("", 4, y, 12, C.sub); radio_lbl:width(w - 10)
y = y + LH12 * (narrow and 3 or 2) + 5

feed_hdr = ui.label(narrow and "recently heard" or "recently heard (newest first)", 4, y, 12, C.sub)
feed_hdr:width(w - 10)
y = y + LH12 + 3
for i = 1, 16 do
feed_rows[i] = ui.label("", 4, y, 12, C.text)
feed_rows[i]:width(w - 10)
y = y + LH12 + 2
end

refresh()
timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_airtime[] = R"WADALUA(


local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local widget = wada.widget


local tr = sys.tr or function(x) return x end
local C = ui.colors
local app = {}

local W, narrow
local head, sub, legend, detail, chart
local base, t0, last
local peak_pct = 0
local spark, wlast = {}, 0

local function restart_window()
local st = mesh.stats()
base = { rx = st.rx_air_s, tx = st.tx_air_s }
t0 = sys.millis()
last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
peak_pct = 0
chart:fill(1, 0)
chart:fill(2, 0)
head:set(tr("sampling..."))
head:color(C.accent)
sys.toast(tr("window restarted"), 900)
end

local function refresh()
local st = mesh.stats()
local now = sys.millis()
local wall = (now - t0) / 1000
if wall < 0.5 then return end

local rx_air, tx_air = st.rx_air_s - base.rx, st.tx_air_s - base.tx
local avg = math.min(100, (rx_air + tx_air) * 100 / wall)

local dw = (now - last.ms) / 1000
local live = 0
if dw > 0 then
live = math.min(100, ((st.rx_air_s - last.rx) + (st.tx_air_s - last.tx)) * 100 / dw)
end
last = { ms = now, rx = st.rx_air_s, tx = st.tx_air_s }
if live > peak_pct then peak_pct = live end

chart:push(1, math.floor(live))
chart:push(2, math.floor(avg))

head:set(string.format(tr("channel busy %.1f%%"), live))
head:color(live > 50 and C.bad or live > 20 and 0xE8A33D or C.good)
sub:set(string.format(tr("avg %.1f%%   peak %.1f%%   over %ds"), avg, peak_pct, math.floor(wall)))
if widget and now - wlast >= 5000 then
wlast = now
spark[#spark + 1] = math.floor(live * 10)
if #spark > 24 then table.remove(spark, 1) end
widget.set{ title = tr("Channel busy"), value = string.format("%.1f%%", live),
line = string.format(tr("avg %.1f%%, peak %.1f%%"), avg, peak_pct), spark = spark }
end
if narrow then
detail:set(string.format("air rx %ds / tx %ds\nduty %d%%   budget %dms\ntx %d  rx %d  err %d",
rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err))
else
detail:set(string.format("air rx %ds / tx %ds   duty %d%%   budget %dms\ntx %d   rx %d   err %d   drop %d   SF%d",
rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err, st.rx_dropped, st.sf))
end
end

function app.on_open(w, h)
W, narrow = w, w < 280
local LH12, LH16 = ui.text_h(12), ui.text_h(16)

local y = 2
head = ui.label(tr("sampling..."), 4, y, 16, C.accent); head:width(w - 86)
ui.button(tr("Reset"), w - 76, y, 70, 30, function() restart_window() end)
y = y + LH16 + 4
sub = ui.label("", 4, y, 12, C.sub); sub:width(w - 10)
y = y + LH12 + 5

local AX = 34
local det_lines = narrow and 3 or 2
local ch_h = h - y - (det_lines * LH12) - LH12 - 14
if ch_h < 48 then ch_h = 48 end
if ch_h > 110 then ch_h = 110 end
chart = ui.chart(w - AX - 8, ch_h, 60, C.accent, 0x4F9DF7, true)
chart:pos(AX, y)
chart:range(0, 100)
chart:axis(3, AX)
y = y + ch_h + 4

legend = ui.label(tr("teal = now   blue = average"), 4, y, 12, C.sub); legend:width(w - 10)
y = y + LH12 + 2
detail = ui.label("", 4, y, 12, C.text); detail:width(w - 10)

local st = mesh.stats()
base = { rx = st.rx_air_s, tx = st.tx_air_s }
t0 = sys.millis()
last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_snake[] = R"WADALUA(

local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local CELL = 14
local app = {}
local cv, score_lbl
local cols, rows, px_w, px_h
local body, len, dx, dy, ndx, ndy, fx, fy
local score, hiscore, running, over

local function place_food()
repeat
fx, fy = sys.random(0, cols - 1), sys.random(0, rows - 1)
local clash = false
for i = 1, len do
if body[i].x == fx and body[i].y == fy then clash = true break end
end
until not clash
end

local function reset()
len, score, over, running = 3, 0, false, false
dx, dy, ndx, ndy = 1, 0, 1, 0
body = {}
local cx, cy = math.floor(cols / 2), math.floor(rows / 2)
for i = 1, len do body[i] = { x = cx - i + 1, y = cy } end
place_food()
end

local function scoreline()
score_lbl:set(string.format("Score %d   Best %d%s", score, hiscore,
running and "" or (over and "   -  tap to retry" or "   -  swipe to start")))
end

local function draw()
cv:fill(0x101418)
cv:rect(fx * CELL + 2, fy * CELL + 2, CELL - 4, CELL - 4, C.bad, true, 4)
for i = len, 1, -1 do
cv:rect(body[i].x * CELL + 1, body[i].y * CELL + 1, CELL - 2, CELL - 2,
i == 1 and C.accent or C.good, true, 3)
end
if over then
cv:text(math.floor(px_w / 2) - 40, math.floor(px_h / 2) - 10, "GAME OVER", C.text, 16)
end
end

local function step()
dx, dy = ndx, ndy
local head = body[1]
local nx, ny = head.x + dx, head.y + dy
if nx < 0 or ny < 0 or nx >= cols or ny >= rows then over = true end
if not over then
for i = 1, len - 1 do
if body[i].x == nx and body[i].y == ny then over = true break end
end
end
if over then
running = false
if score > hiscore then
hiscore = score
store.set("hiscore", hiscore)
sys.toast("New high score: " .. hiscore, 1600)
end
scoreline()
draw()
return
end
table.insert(body, 1, { x = nx, y = ny })
if nx == fx and ny == fy then
len = len + 1
score = score + 10
place_food()
scoreline()
else
body[#body] = nil
end
draw()
end

function app.on_open(w, h)
hiscore = store.get("hiscore", 0)
cols = math.floor(w / CELL)
rows = math.floor((h - 26) / CELL)
px_w, px_h = cols * CELL, rows * CELL
score_lbl = ui.label("", 4, 4, 14, C.text)
cv = ui.canvas(px_w, px_h)
cv:pos(math.floor((w - px_w) / 2), 26)
reset()
scoreline()
draw()
timer.every(120)
end

function app.on_input(ev)
if ev.type == "swipe" then
local d = ev.dir
if     d == "up"    and dy ~= 1  then ndx, ndy = 0, -1
elseif d == "down"  and dy ~= -1 then ndx, ndy = 0, 1
elseif d == "left"  and dx ~= 1  then ndx, ndy = -1, 0
elseif d == "right" and dx ~= -1 then ndx, ndy = 1, 0
end
if not running and not over then running = true; scoreline() end
elseif ev.type == "down" and over then
reset()
scoreline()
draw()
end
end

function app.on_tick(dt)
if running and not over then step() end
end

function app.on_close()


end

return app
)WADALUA";
#if CAP_LUA_SDK_EXT
static const char kLuaSrc_sdktest[] = R"WADALUA(























local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local app = {}
local rows, keyline, sendline, dmline, msgline = {}, nil, nil, nil, nil
local discline, inputline = nil, nil
local W = 300






local LH, GAP = 14, 3
local cy = 4
local function row(text, color, extra_gap)
local l = ui.label(text, 6, cy, 12, color or C.text)
l:width(W - 12)
rows[#rows + 1] = l
local n
if ui.text_lines then
n = ui.text_lines(tostring(text), W - 12, 12)
else
local cpl = math.max(16, (W - 12) // 7)
n = 0
for seg in (tostring(text) .. "\n"):gmatch("(.-)\n") do
n = n + math.max(1, math.ceil(#seg / cpl))
end
end
cy = cy + math.max(1, n or 1) * LH + GAP + (extra_gap or 0)
return l
end
local function yn(v) return v and "yes" or "NO" end

function app.on_open(w, h)
W = w or 300
ui.scroll(true)
cy = 4
local y

local c = sys.caps()
row("caps: sdk_ext=" .. yn(c.sdk_ext) .. "  kbd=" .. yn(c.keyboard) ..
"  touch=" .. yn(c.touch) .. "  sd=" .. yn(c.sd), C.accent)
row("caps: sd_list=" .. yn(c.sd_list) .. "  discover=" .. yn(c.discover) ..
"  input=" .. yn(c.input) ..
"  rx_identity=" .. yn(c.rx_identity), C.accent)
row("caps: audio=" .. yn(c.audio) .. "  wav=" .. yn(c.audio_wav) ..
"  mp3=" .. yn(c.audio_mp3) .. "  audio_sd=" .. yn(c.audio_sd), C.accent)
if c.audio then
local api_ok = wada.audio and type(wada.audio.play) == "function" and
type(wada.audio.pause) == "function" and
type(wada.audio.resume) == "function" and
type(wada.audio.stop) == "function" and
type(wada.audio.status) == "function"
local status = api_ok and wada.audio.status() or nil
api_ok = api_ok and type(status) == "table" and type(status.state) == "string"
row("wada.audio API: " .. (api_ok and ("PASS (" .. status.state .. ")") or "FAIL"),
api_ok and C.good or C.bad)
else
row("wada.audio: unavailable on this board", C.sub)
end
row("layout: " .. (ui.text_lines and "measured (ui.text_lines)" or "estimated (older firmware)"),
ui.text_lines and C.good or C.sub)

if wada.crypto then
local hex = wada.crypto.hex
local k20 = string.rep(string.char(0x0b), 20)
local checks = {
{ "sha256('abc')", hex(wada.crypto.sha256("abc")),
"ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" },
{ "sha1('abc')", hex(wada.crypto.sha1("abc")),
"a9993e364706816aba3e25717850c26c9cd0d89d" },
{ "hmac_sha1 RFC2202#1", hex(wada.crypto.hmac_sha1(k20, "Hi There")),
"b617318655057264e28bc0b6fb378c8ef146be00" },
{ "hmac_sha256 RFC4231#1", hex(wada.crypto.hmac_sha256(k20, "Hi There")),
"b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7" },
}
local allok = true
for _, t in ipairs(checks) do
local ok = (t[2] == t[3])
if not ok then allok = false end
row("crypto " .. t[1] .. ": " .. (ok and "PASS" or ("FAIL got " .. tostring(t[2]):sub(1, 16))),
ok and C.good or C.bad)
end

local t0 = sys.millis()
for _ = 1, 200 do wada.crypto.hmac_sha1(k20, "Hi There") end
row(string.format("crypto: 200 x hmac_sha1 in %d ms%s", sys.millis() - t0,
allok and "" or "  (VECTORS FAILED)"), allok and C.good or C.bad)
else
row("wada.crypto: MISSING", C.bad)
end


local chans = wada.mesh.channels and wada.mesh.channels() or nil
if chans then
local names = table.concat(chans, ", ")
row("channels(): " .. #chans .. "  " .. names:sub(1, 60), C.text)
else
row("wada.mesh.channels: MISSING", C.bad)
end

if not c.sdk_ext then
row("extended SDK is OFF on this board - stopping here.", C.sub)
return
end


local cts = wada.mesh.contacts()
local first = cts[1] and cts[1].name or nil
row("contacts: " .. #cts .. (first and ("  first=" .. first) or ""), C.text)
if cts[1] then
local pk = cts[1].pubkey
row("contacts[1].pubkey: " .. tostring(pk) ..
(type(pk) == "string" and #pk == 8 and "  PASS" or "  FAIL"),
(type(pk) == "string" and #pk == 8) and C.good or C.bad)
end

local me = wada.mesh.self()
row("self: " .. tostring(me.name) .. "  pubkey=" .. tostring(me.pubkey), C.text)


local fix = sys.gps()
if fix then
local drift = math.abs(fix.lat_e6 / 1e6 - fix.lat)
row(string.format("gps: %d,%d e6  alt %dm  %d sats  drift %.6f  %s",
fix.lat_e6, fix.lon_e6, fix.alt_m or 0, fix.sats, drift,
drift < 0.001 and "PASS" or "FAIL"), drift < 0.001 and C.good or C.bad)
else
row("gps: no fix (normal indoors)", C.sub)
end



local log = wada.mesh.rx_log()
local withpk, withsrc = 0, 0
for _, r in ipairs(log) do
if r.pubkey then withpk = withpk + 1 end
if r.src then withsrc = withsrc + 1 end
end
row(string.format("rx_log: %d frames, %d with a pubkey (adverts), %d with src/dst",
#log, withpk, withsrc), #log > 0 and C.text or C.sub)

if wada.fs then
local probe = "0123456789abcdef"
wada.fs.write("sdktest.bin", probe)
local part, total = wada.fs.read("sdktest.bin", 4, 4)
local ok = (part == "4567" and total == #probe)
row("fs.read(name,4,4): " .. tostring(part) .. " total=" .. tostring(total) ..
(ok and "  PASS" or "  FAIL"), ok and C.good or C.bad)
end




if c.sd_list then
if not wada.sd or not wada.sd.list then
row("wada.sd.list: MISSING despite caps", C.bad)
else
local guard_ok, guard_failure = true, nil
local bad_paths = { "/..", "/.", "/a/../b", "/a//b", "/a/", "relative", "/a\\b" }
for _, path in ipairs(bad_paths) do
local rejected, baderr = wada.sd.list(path)
if rejected ~= nil or baderr ~= "bad path" then
guard_ok = false
guard_failure = path .. " -> " .. tostring(baderr)
break
end
end
row("sd traversal guard: " .. (guard_ok and "PASS" or ("FAIL " .. guard_failure)),
guard_ok and C.good or C.bad)

local entries, err = wada.sd.list("/")
if not entries then
local note = err == "busy" and " (retry later)" or " (no readable card)"
row("sd.list('/'): " .. tostring(err) .. note, C.sub)
else
local metadata_ok, first_dir = true, nil
for _, entry in ipairs(entries) do
if type(entry.name) ~= "string" or
(entry.type ~= "file" and entry.type ~= "dir") or
type(entry.size) ~= "number" or type(entry.mtime) ~= "number" then
metadata_ok = false
end
if not first_dir and entry.type == "dir" then first_dir = entry.name end
end
row("sd.list('/'): " .. #entries .. " entries, metadata " ..
(metadata_ok and "PASS" or "FAIL") ..
(entries.truncated and " (truncated)" or ""),
metadata_ok and C.good or C.bad)
if first_dir then
local nested, nested_err = wada.sd.list("/" .. first_dir)
row("sd.list('/" .. first_dir .. "'): " ..
(nested and (#nested .. " entries PASS") or ("FAIL " .. tostring(nested_err))),
nested and C.good or C.bad)
else
row("sd nested listing: no directory on card to test", C.sub)
end
end
end
else
row("wada.sd.list: unavailable on this board", C.sub)
end

sendline = row("mesh.send: not tried yet", C.sub)
dmline   = row("mesh.send_dm: not tried yet", C.sub)
msgline  = row("on_message: waiting (needs the read permissions)", C.sub)
y = cy + 4
ui.button("Send to Public", 6, y, 120, 30, function()
local ok, err = wada.mesh.send("Public", "wadamesh SDK self-test")
sendline:set("mesh.send: " .. tostring(ok) .. "  " .. tostring(err))
sendline:color(ok and C.good or C.bad)
end)
ui.button("DM first contact", 132, y, 130, 30, function()
if not first then dmline:set("mesh.send_dm: no contacts to target"); dmline:color(C.bad); return end
local ok, err = wada.mesh.send_dm(first, "wadamesh SDK self-test (DM)")
dmline:set("mesh.send_dm -> " .. first .. ": " .. tostring(ok) .. "  " .. tostring(err))
dmline:color(ok and C.good or C.bad)
end)
cy = y + 38
discline  = row("mesh.discover: not tried yet", C.sub)
inputline = row("ui.input: not tried yet", C.sub)


y = cy + 4
ui.button("Probe", 6, y, 90, 30, function()
local tag, err = wada.mesh.discover()
if not tag then
discline:set("mesh.discover: " .. tostring(err)); discline:color(C.bad); return
end
discline:set("mesh.discover: sent, waiting for replies..."); discline:color(C.text)
end)
ui.button("Results", 102, y, 90, 30, function()
local hits = wada.mesh.discovered()
if #hits == 0 then
discline:set("discovered(): nothing yet - probe, then wait a few seconds")
discline:color(C.sub); return
end
local h = hits[1]
discline:set(string.format("discovered(): %d  first %s snr %.1f/%.1f %s",
#hits, h.name or h.pubkey, h.snr, h.their_snr, h.direct and "direct" or (h.hops .. "h")))
discline:color(C.good)
end)
y = y + 34
ui.button("Beep", 6, y, 70, 30, function() sys.beep() end)
ui.button("Input", 82, y, 90, 30, function()
ui.input("Type anything", "hello", function(text)
inputline:set("ui.input -> " .. (text and ("'" .. text .. "'") or "cancelled"))
inputline:color(text and C.good or C.sub)
end)
end)
end

function app.on_input(ev)
if ev.type == "key" and keyline then
keyline:set("keys: got '" .. tostring(ev.key) .. "'")
keyline:color(C.good)
end
end


function app.on_message(m)
if not msgline then return end
msgline:set("on_message: kind=" .. tostring(m.kind) .. " from=" .. tostring(m.sender) ..
" ch=" .. tostring(m.channel) .. " text=" .. tostring(m.text):sub(1, 20))
msgline:color(C.good)
end

return app
)WADALUA";
#endif
#if CAP_LUA_SDK_EXT
static const char kLuaSrc_wardrive[] = R"WADALUA(




















local ui, sys, mesh, fs, timer = wada.ui, wada.sys, wada.mesh, wada.fs, wada.timer
local C = ui.colors
local app = {}



local clear = ui.clear or function() end
local tr = sys.tr or function(x) return x end

local SWEEP_MS = 20000
local HARVEST_MS = 4000



local STALE_MS = HARVEST_MS + 3000
local TYPE = { [1]="chat", [2]="repeater", [3]="room", [4]="sensor" }

local run, running, samples, sweeps, last_err = "run", false, 0, 0, nil


local dropped_sweeps = 0
local node_count = 0
local phase, phase_at = "idle", 0


local function harvest_fresh(now) return (now - phase_at) <= STALE_MS end
local hdr, gps_lbl, stat_lbl, rows = nil, nil, nil, {}
local nodes = {}
local pending = {}





local W, H = 0, 0
local view = "survey"
local was_running = false
local MODES = { "heard them", "heard us", "asymmetry" }
local mode = 1
local map, map_note, rv_stat, rv_legend, rv_plot = nil, nil, nil, nil, nil
local plot_px = 0



local ld = nil
local READ_WIN = 4096



local MAX_DRAW = 150

local function logname() return run .. ".csv" end





local function utf8_prefix_bytes(text, max_bytes)
local offset, last, length = 1, 0, #text
while offset <= length and offset <= max_bytes do
local first = text:byte(offset)
local width = first <= 0x7F and 1
or (first >= 0xC2 and first <= 0xDF and 2)
or (first >= 0xE0 and first <= 0xEF and 3)
or (first >= 0xF0 and first <= 0xF4 and 4) or 0
if width == 0 or offset + width - 1 > length or offset + width - 1 > max_bytes then break end
local valid = true
for i = 2, width do
local byte = text:byte(offset + i - 1)
if byte < 0x80 or byte > 0xBF then valid = false; break end
end
local second = width > 1 and text:byte(offset + 1) or 0
if (first == 0xE0 and second < 0xA0) or (first == 0xED and second > 0x9F) or
(first == 0xF0 and second < 0x90) or (first == 0xF4 and second > 0x8F) then valid = false end
if not valid then break end
last = offset + width - 1
offset = last + 1
end
return text:sub(1, last)
end





local HEADER = "epoch,lat_e6,lon_e6,alt_m,pubkey,name,type,rssi,snr,their_snr,hops"



local wrote_header = nil



local function flush()
if #pending == 0 then return end
local chunk = table.concat(pending, "\n") .. "\n"
if wrote_header == nil then
local d = fs.read(logname(), 0, 8)
wrote_header = (d ~= nil and #d > 0)
end
if not wrote_header then chunk = HEADER .. "\n" .. chunk end
local ok = fs.append(logname(), chunk)
if ok then pending, wrote_header = {}, true end
end

local function record(fix, hit)
local key = hit.pubkey
local n = nodes[key]
if not n then
n = { name = hit.name or key, type = hit.type, best = hit.snr, worst = hit.snr, seen = 0 }
nodes[key] = n
node_count = node_count + 1
end
if hit.snr > n.best  then n.best  = hit.snr end
if hit.snr < n.worst then n.worst = hit.snr end
n.seen = n.seen + 1
if hit.name then n.name = hit.name end

samples = samples + 1
pending[#pending + 1] = string.format("%d,%d,%d,%d,%s,%s,%d,%d,%.2f,%.2f,%d",
fix.time or sys.epoch() or 0, fix.lat_e6, fix.lon_e6, fix.alt_m or 0,
key, (hit.name or ""):gsub(",", " "), hit.type,
hit.rssi, hit.snr, hit.their_snr, hit.hops)
end

local function sweep()
local tag, err = mesh.discover()
if not tag then last_err = err; return false end
last_err = nil
sweeps = sweeps + 1
return true
end

local function harvest()
local fix = sys.gps()
if not fix then



mesh.discover_clear()
return
end
for _, hit in ipairs(mesh.discovered()) do record(fix, hit) end
mesh.discover_clear()
end

local function redraw()
local fix = sys.gps()
if fix then
gps_lbl:set(string.format("%.5f, %.5f  %dm  %d sats", fix.lat, fix.lon, fix.alt_m or 0, fix.sats))
gps_lbl:color(C.good)
else
gps_lbl:set(tr("waiting for a GPS fix - samples are discarded until then"))
gps_lbl:color(C.bad)
end

local state = running and (phase == "probe" and "listening..." or "sweeping") or "stopped"
stat_lbl:set(string.format("%s  |  %s  |  %d sweeps, %d samples, %d nodes%s%s",
run, state, sweeps, samples, node_count,
dropped_sweeps > 0 and ("  ·  " .. dropped_sweeps .. " dropped") or "",
last_err and ("  [" .. last_err .. "]") or ""))
stat_lbl:color(last_err and C.bad or C.accent)

local list = {}
for key, n in pairs(nodes) do list[#list + 1] = { key = key, n = n } end
table.sort(list, function(a, b) return a.n.best > b.n.best end)
for i = 1, #rows do
local e = list[i]
if e then
rows[i]:set(string.format("%-14s %-8s best %5.1f  worst %5.1f  x%d",
utf8_prefix_bytes(e.n.name, 14), TYPE[e.n.type] or "?", e.n.best, e.n.worst, e.n.seen))
rows[i]:color(e.n.best > 0 and C.good or C.text)
else
rows[i]:set(i == 1 and tr("nothing has answered a probe yet") or "")
rows[i]:color(C.sub)
end
end
end











local function metric_of(st)
if mode == 2 then return st.them_max end
if mode == 3 then return st.asym end
return st.snr_max
end

local function colour_for(v)
if mode == 3 then

if v > 6 or v < -6 then return C.bad end
if v > 3 or v < -3 then return C.accent end
return C.good
end
if v >= 0 then return C.good end
if v >= -10 then return C.accent end
return C.bad
end

local function ld_reset()


ld = { off = 0, total = nil, tail = "", stops = {}, n = 0, skipped = 0, done = false, plotted = false,
minlat = nil, maxlat = nil, minlon = nil, maxlon = nil, metres = 0, wrapped = false,
prev_lat = nil, prev_lon = nil, by_node = {}, node_n = 0, step = 1,
stop_n = 0, pos_i = 0, keep_every = 1, last_key = nil, cur = nil, tailstop = nil }
end

local MAX_STOPS = 400
local function stop_push(lat, lon)
ld.pos_i = ld.pos_i + 1
ld.stop_n = ld.stop_n + 1
if #ld.stops >= MAX_STOPS then


local last = ld.stops[#ld.stops]
local out, j = {}, 0
for i = 1, #ld.stops, 2 do j = j + 1; out[j] = ld.stops[i] end
if out[j] ~= last then j = j + 1; out[j] = last end
ld.stops = out
ld.keep_every = ld.keep_every * 2
end


local st = { lat = lat, lon = lon, n = 0 }
ld.tailstop = st
if (ld.pos_i % ld.keep_every) == 0 then
ld.stops[#ld.stops + 1] = st
st.kept = true
end
return st
end


local function stops_finalise()
local t = ld and ld.tailstop
if t and not t.kept and #ld.stops > 0 then
ld.stops[#ld.stops + 1] = t
t.kept = true
end
end

local function ld_row(line)



local f, n = {}, 0
for part in (line .. ","):gmatch("([^,]*),") do
n = n + 1; f[n] = part
if n >= 11 then break end
end
if n < 11 then ld.skipped = ld.skipped + 1; return end
local lat_e6, lon_e6 = tonumber(f[2]), tonumber(f[3])
local snr, their = tonumber(f[9]), tonumber(f[10])
if not (lat_e6 and lon_e6 and snr and their) then ld.skipped = ld.skipped + 1; return end
local lat, lon = lat_e6 / 1000000, lon_e6 / 1000000


if lat_e6 == 0 and lon_e6 == 0 then ld.skipped = ld.skipped + 1; return end

ld.n = ld.n + 1
if not ld.minlat or lat < ld.minlat then ld.minlat = lat end
if not ld.maxlat or lat > ld.maxlat then ld.maxlat = lat end
if not ld.minlon or lon < ld.minlon then ld.minlon = lon end
if not ld.maxlon or lon > ld.maxlon then ld.maxlon = lon end

if ld.prev_lat and wada.geo then
local ok, d = pcall(wada.geo.distance, ld.prev_lat, ld.prev_lon, lat, lon)
if ok and d then ld.metres = ld.metres + d end
end
ld.prev_lat, ld.prev_lon = lat, lon

local key = f[5]
local nd = ld.by_node[key]
if not nd then
nd = { name = (f[6] ~= "" and f[6]) or key, type = tonumber(f[7]) or 0,
best = snr, worst = snr, best_them = their, asym = snr - their, seen = 0 }
ld.by_node[key] = nd
ld.node_n = ld.node_n + 1
end
if snr > nd.best then nd.best = snr end
if snr < nd.worst then nd.worst = snr end
if their > nd.best_them then nd.best_them = their end


do
local a = snr - their
if (a < 0 and -a or a) > (nd.asym < 0 and -nd.asym or nd.asym) then nd.asym = a end
end
nd.seen = nd.seen + 1




local ekey = f[2] .. "," .. f[3]
if ekey ~= ld.last_key then
ld.last_key = ekey
ld.cur = stop_push(lat, lon)
end
local st = ld.cur
if st then
st.n = st.n + 1
if not st.snr_max  or snr   > st.snr_max  then st.snr_max  = snr   end
if not st.snr_min  or snr   < st.snr_min  then st.snr_min  = snr   end
if not st.them_max or their > st.them_max then st.them_max = their end
if not st.them_min or their < st.them_min then st.them_min = their end
local a = snr - their
if not st.asym or (a < 0 and -a or a) > (st.asym < 0 and -st.asym or st.asym) then st.asym = a end
end
end


local function ld_step()
if not ld or ld.done then return false end
local data, total = fs.read(logname(), ld.off, READ_WIN)
if not data then


if ld.tail ~= "" and not ld.tail:find("^epoch,") then ld_row(ld.tail); ld.tail = "" end
stops_finalise()
ld.done = true
return false
end
ld.total = total or (ld.off + #data)
ld.off = ld.off + #data
local buf = ld.tail .. data
local last = 0
for line, pos in buf:gmatch("([^\n]*)\n()") do
last = pos - 1
if line ~= "" and not line:find("^epoch,") then ld_row(line) end
end
ld.tail = buf:sub(last + 1)



if #data == 0 then
if ld.tail ~= "" and not ld.tail:find("^epoch,") then ld_row(ld.tail) end
ld.tail = ""
stops_finalise()
ld.done = true
end
return not ld.done
end










local function merc_y(lat)

if lat >  85 then lat =  85 end
if lat < -85 then lat = -85 end
local r = lat * math.pi / 180
return 0.5 - math.log(math.tan(math.pi / 4 + r / 2)) / (2 * math.pi)
end





local function merc_lat(y)
local r = 2 * (math.atan(math.exp((0.5 - y) * 2 * math.pi)) - math.pi / 4)
return r * 180 / math.pi
end

local function fit_zoom(px, py)
if not ld or not ld.minlat then return 14 end
local sy = math.max(math.abs(merc_y(ld.minlat) - merc_y(ld.maxlat)), 1e-9)



local sx = (ld.maxlon - ld.minlon) / 360
if sx > 0.5 then ld.wrapped = true end
sx = math.max(sx, 1e-9)
local function z_for(span_norm, pixels)
if not (pixels > 0) then return 1 end
local v = pixels / (256 * span_norm)
if not (v > 1) then return 1 end
return math.floor(math.log(v) / math.log(2))
end
local z = ld.wrapped and z_for(sy, py) or math.min(z_for(sx, px), z_for(sy, py))


if not (z == z) then z = 14 end
if z < 1 then z = 1 end
if z > 19 then z = 19 end
return z
end

local function review_plot()
if not ld then return end
local drawn = 0
local step = math.max(1, math.ceil(#ld.stops / MAX_DRAW))
ld.step = step
if map then
map:clear()
if ld.minlat then



local clat = merc_lat((merc_y(ld.minlat) + merc_y(ld.maxlat)) / 2)
local clon
if ld.wrapped then


local a = ld.minlon < 0 and ld.minlon + 360 or ld.minlon
local b = ld.maxlon < 0 and ld.maxlon + 360 or ld.maxlon
clon = (a + b) / 2
if clon > 180 then clon = clon - 360 end
else
clon = (ld.minlon + ld.maxlon) / 2
end
map:center(clat, clon, fit_zoom(W - 8, plot_px))




local prev = nil
for i = 1, #ld.stops, step do
local st = ld.stops[i]
if prev then map:line(prev.lat, prev.lon, st.lat, st.lon, C.sub, 1) end
if map:marker(st.lat, st.lon, colour_for(metric_of(st)), 3) then drawn = drawn + 1 end
prev = st
end
end
local tiles = 0
local ok, t = pcall(function() return map:tiles() end)
if ok and t then tiles = t end
if not ld.minlat then


map_note:set("")
elseif tiles == 0 then


map_note:set(tr("no tiles cached here - blank ground, not open water"))
map_note:color(C.bad)
else
map_note:set(string.format("%d tiles  ·  %d of %d stops drawn%s%s", tiles, drawn, ld.stop_n,
step > 1 and ("  ·  1 in " .. step) or "",
ld.keep_every > 1 and ("  ·  sampled 1 in " .. ld.keep_every .. " while reading") or ""))
map_note:color(C.sub)
end
elseif rv_plot then






local pw, ph = math.min(W - 8, 480), math.min(plot_px, 480)
rv_plot:fill(C.bg)
if ld.minlat then
local dlat = math.max(ld.maxlat - ld.minlat, 1e-6)
local dlon = math.max(ld.maxlon - ld.minlon, 1e-6)
local function sx(lon) return math.floor(4 + (lon - ld.minlon) / dlon * (pw - 8)) end
local function sy(lat) return math.floor(4 + (ld.maxlat - lat) / dlat * (ph - 8)) end
local prev = nil
for i = 1, #ld.stops, step do
local st = ld.stops[i]
local x, y = sx(st.lon), sy(st.lat)
if prev then rv_plot:line(prev[1], prev[2], x, y, C.sub) end
rv_plot:circle(x, y, 2, colour_for(metric_of(st)))
drawn = drawn + 1
prev = { x, y }
end
end
rv_plot:text(4, 2, string.format(tr("route shape, not to scale - %d of %d stops"), drawn, ld.stop_n), C.sub, 12)
end
end

local function review_stat()
if not ld then return end
if not ld.done then
rv_stat:set(string.format(tr("reading %s ... %d rows"), logname(), ld.n))
rv_stat:color(C.sub)
return
end
if ld.n == 0 then
rv_stat:set(string.format(tr("%s holds no plottable rows yet"), logname()))
rv_stat:color(C.bad)
return
end
local km = ld.metres / 1000
rv_stat:set(string.format("%s  ·  %d samples at %d stops, %d nodes  ·  %.2f km%s%s",
run, ld.n, ld.stop_n, ld.node_n, km,
ld.wrapped and "  ·  crosses the antimeridian, fitted on latitude only" or "",
ld.skipped > 0 and ("  ·  " .. ld.skipped .. " unusable") or ""))
rv_stat:color(C.accent)


local worst_name, worst_gap = nil, nil
for _, nd in pairs(ld.by_node) do
local g = nd.asym < 0 and -nd.asym or nd.asym
if not worst_gap or g > worst_gap then worst_gap, worst_name = g, nd.name end
end
local legend
if mode == 3 then
legend = tr("colour: balance, green even, red one-sided")
if worst_name then
legend = legend .. string.format("  ·  worst %s %.1f dB",
utf8_prefix_bytes(worst_name, 10), worst_gap)
end
elseif mode == 2 then
legend = tr("colour: how well they heard US")
else
legend = tr("colour: how well WE heard them")
end
rv_legend:set(legend)
rv_legend:color(C.sub)
end



local build_survey, build_review










local function drop_map()
if map then pcall(function() map:close() end) end
map = nil
end

local function enter_review()








if running and phase == "probe" and harvest_fresh(sys.millis()) then
harvest()
else
if phase == "probe" then dropped_sweeps = dropped_sweeps + 1 end
mesh.discover_clear()
end
flush()
was_running = running
running = false
phase = "idle"
view = "review"
ld_reset()
build_review()
end

local function leave_review()
drop_map()
view = "survey"
running = was_running
if running then phase, phase_at = "idle", 0 end
mesh.discover_clear()
ld = nil
build_survey()
end

build_review = function()
drop_map()
clear()
ui.scroll(true)
hdr, gps_lbl, stat_lbl, rows = nil, nil, nil, {}
local LH = ui.text_h(12)
local y = 4
ui.label(tr("Run review"), 4, y, 12, C.accent); y = y + LH + 3
rv_stat = ui.label("", 4, y, 12, C.text); rv_stat:width(W - 10); y = y + LH * 2 + 3



local BTN_H = 32
local reserved = 4 + (LH + 3) + (LH * 2 + 3) + 4 + (LH * 2 + 2) + (LH * 2 + 3) + BTN_H + 4
local plot_h = math.max(40, H - reserved)
plot_px = plot_h
rv_plot = nil
if sys.caps().map then



local ok, m = pcall(function() return wada.map.view(4, y, W - 8, plot_h) end)
if ok and m then map = m end
end
if not map then



local okc, cv = pcall(ui.canvas, math.min(W - 8, 480), math.min(plot_h, 480))
if okc and cv then rv_plot = cv; rv_plot:pos(4, y) end
end
y = y + plot_h + 4

map_note = ui.label("", 4, y, 12, C.sub); map_note:width(W - 10); y = y + LH * 2 + 2
rv_legend = ui.label("", 4, y, 12, C.sub); rv_legend:width(W - 10); y = y + LH * 2 + 3

local bw = math.min(96, (W - 20) // 3)
ui.button(tr("Back"), 4, y, bw, 32, function() leave_review() end)
ui.button(tr("Colour"), 8 + bw, y, bw, 32, function()
mode = mode % #MODES + 1
sys.toast(MODES[mode], 1000)
review_plot(); review_stat()
end)


ui.button(tr("Refit"), 12 + bw * 2, y, bw, 32, function()
ld_reset()
review_stat()
end)

review_stat()
end

build_survey = function()
drop_map()
clear()
rv_plot, rv_stat, rv_legend, map_note = nil, nil, nil, nil
ui.scroll(true)
local LH = ui.text_h(12)
local y = 4

hdr = ui.label(tr("LoRa coverage survey"), 4, y, 12, C.accent); hdr:width(W - 10); y = y + LH + 3
gps_lbl = ui.label("", 4, y, 12, C.sub); gps_lbl:width(W - 10); y = y + LH + 3
stat_lbl = ui.label("", 4, y, 12, C.text); stat_lbl:width(W - 10); y = y + LH * 2 + 5

local bw = math.min(96, (W - 20) // 3)
ui.button(tr("Start"), 4, y, bw, 32, function()
running = not running
if running then phase, phase_at = "idle", 0 end
sys.toast(running and tr("Survey running") or tr("Survey stopped"), 1200)
end)
ui.button(tr("Name"), 8 + bw, y, bw, 32, function()
ui.input(tr("Name this run"), run, function(text)
if text then


flush()
pending = {}
run = text:gsub("[^%w%-_]", "_")
wrote_header = nil
sys.toast("Logging to " .. logname(), 1500)
end
end)
end)
ui.button(tr("Reset"), 12 + bw * 2, y, bw, 32, function()
nodes, samples, sweeps, pending, node_count = {}, 0, 0, {}, 0
dropped_sweeps = 0
mesh.discover_clear()
fs.remove(logname())
wrote_header = nil
sys.toast("Cleared " .. logname(), 1200)
end)
y = y + 38




ui.button(tr("Review run"), 4, y, math.min(bw * 2 + 4, W - 8), 32, function()
enter_review()
end)
y = y + 38

ui.label(tr("strongest first"), 4, y, 12, C.sub); y = y + LH + 2
for i = 1, 12 do
rows[i] = ui.label("", 4, y, 12, C.text); rows[i]:width(W - 10); y = y + LH + 2
end

redraw()
end

function app.on_open(w, h)
W, H = w, h


if not sys.caps().discover then
ui.label(tr("This board cannot send discovery probes,"), 6, 8, 12, C.bad)
ui.label(tr("so it cannot run a coverage survey."), 6, 26, 12, C.bad)
return
end
build_survey()
timer.every(1000)
end

function app.on_tick()


if view == "review" then
local more = ld_step()
review_stat()
if not more and ld and ld.done and not ld.plotted then
ld.plotted = true
review_plot()
end
flush()
return
end

if running then
local now = sys.millis()
if phase == "idle" or (phase == "wait" and now - phase_at >= SWEEP_MS) then


phase, phase_at = sweep() and "probe" or "wait", now
elseif phase == "probe" and now - phase_at >= HARVEST_MS then




if harvest_fresh(now) then
harvest()
else
mesh.discover_clear()
dropped_sweeps = dropped_sweeps + 1
end
phase = "wait"
end
end
flush()
redraw()
end

function app.on_close()
flush()
drop_map()
end

return app
)WADALUA";
#endif
#if CAP_LUA_SDK_EXT
static const char kLuaSrc_nearby[] = R"WADALUA(






local ui, sys, mesh, geo, timer = wada.ui, wada.sys, wada.mesh, wada.geo, wada.timer
local C = ui.colors
local app = {}

local map, list, hdr, detail = nil, nil, nil, nil
local pts, sel = {}, 0
local pkt_count, pkt_adverts = 0, 0
local W, H

local function here()
local fix = sys.gps()
if fix then return fix.lat, fix.lon, true end
local me = mesh.self()


if me.lat ~= 0 or me.lon ~= 0 then return me.lat, me.lon, false end
return nil
end

local function fmt_dist(m)
if m < 1000 then return string.format("%.0f m", m) end
return string.format("%.1f km", m / 1000)
end

local function rebuild()
local lat, lon, live = here()
pts, sel = {}, 0
for _, c in ipairs(mesh.contacts()) do
if c.lat ~= 0 or c.lon ~= 0 then
local e = { name = c.name, lat = c.lat, lon = c.lon, type = c.type, pubkey = c.pubkey }
if lat then
e.dist = geo.distance(lat, lon, c.lat, c.lon)
e.brg  = geo.bearing(lat, lon, c.lat, c.lon)
end
pts[#pts + 1] = e
end
end
if lat then table.sort(pts, function(a, b) return (a.dist or 1e9) < (b.dist or 1e9) end) end

list:clear()
for i, e in ipairs(pts) do
local label = e.dist
and string.format("%-12s  %8s  %-2s", e.name:sub(1, 12), fmt_dist(e.dist), geo.cardinal(e.brg))
or  e.name
list:add(label, function() app.pick(i) end)
end
if #pts == 0 then list:add("no contacts have a position yet") end

hdr:set(string.format("%d placed  |  %s  |  %d frames (%d adverts)",
#pts, lat and (live and "GPS fix" or "last known position") or "no position", pkt_count, pkt_adverts))
hdr:color(lat and C.accent or C.bad)

if lat then app.draw(lat, lon) end
end

function app.draw(lat, lon)
if not map then return end
map:center(lat, lon)
map:clear()
if map:tiles() == 0 then

detail:set("no map tiles cached here at zoom " .. map:zoom())
detail:color(C.sub)
end
for i, e in ipairs(pts) do
map:line(lat, lon, e.lat, e.lon, i == sel and C.good or 0x2A3340, i == sel and 2 or 1)
end
for i, e in ipairs(pts) do
map:marker(e.lat, e.lon, i == sel and C.good or C.accent, i == sel and 12 or 8)
end
map:marker(lat, lon, 0xE8A33D, 10)
end

function app.pick(i)
sel = i
list:select(i)
local e = pts[i]
if not e then return end
local lat, lon = here()
if e.dist then
detail:set(string.format("%s  %s  %.0f deg (%s)  %s",
e.name, fmt_dist(e.dist), e.brg, geo.cardinal(e.brg), e.pubkey))
else
detail:set(e.name .. "  " .. e.pubkey)
end
detail:color(C.text)
if lat then app.draw(lat, lon) end
end

function app.on_open(w, h)
W, H = w, h
local LH = ui.text_h(12)
hdr = ui.label("", 4, 4, 12, C.accent); hdr:width(w - 10)




local map_h = math.floor(h * 0.45)
local y = 4 + LH * 2 + 4
if sys.caps().map then
map = wada.map.view(4, y, w - 8, map_h)
else
ui.label("this board has no map support", 6, y + 10, 12, C.sub)
end
y = y + map_h + 4

detail = ui.label("pick a contact", 4, y, 12, C.sub); detail:width(w - 10)
y = y + LH * 2 + 4

list = ui.list(4, y, w - 8, h - y - 4)

rebuild()



timer.every(5000, rebuild)
end



function app.on_packet(p)
pkt_count = pkt_count + 1
if p.pubkey then pkt_adverts = pkt_adverts + 1 end
end

function app.on_close()
if map then map:close() end
end

return app
)WADALUA";
#endif
#if CAP_LUA_SDK_EXT
static const char kLuaSrc_ping[] = R"WADALUA(






local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local mesh = wada.mesh
local geo   = wada.geo
local C = ui.colors

local app = {}

local PING_PFX = "WADAPING:"
local PONG_PFX = "WADAPONG:"

local W, H
local gps_lbl
local rows = {}
local pending = {}



local function gps_line()
local fix = sys.gps()
if not fix then return "no GPS fix" end
local ns = fix.lat >= 0 and "N" or "S"
local ew = fix.lon >= 0 and "E" or "W"
return string.format("%.4f°%s  %.4f°%s  %d sats",
math.abs(fix.lat), ns, math.abs(fix.lon), ew, fix.sats or 0)
end

local function dist_str(m)
if m < 1000 then return string.format("%dm", math.floor(m + 0.5))
else return string.format("%.1fkm", m / 1000.0) end
end

local function find_row(name)
for _, r in ipairs(rows) do
if r.name == name then return r end
end
end

local function set_row_result(name, rtt_ms, dist_m, cardinal)
local r = find_row(name)
if not r then return end
if rtt_ms then
local s = tostring(rtt_ms) .. "ms"
if dist_m and dist_m > 0 then
s = s .. "  " .. dist_str(dist_m)
if cardinal then s = s .. "  " .. cardinal end
end
r.result_lbl:set(s)
r.result_lbl:color(C.good)
else
r.result_lbl:set("waiting…")
r.result_lbl:color(C.sub)
end
end

local function do_ping(name)
local fix  = sys.gps()
local lat6 = fix and fix.lat_e6 or 0
local lon6 = fix and fix.lon_e6 or 0
local ts   = sys.millis()
local msg  = string.format("%s%d:%d:%d", PING_PFX, ts, lat6, lon6)
local ok, err = mesh.send_dm(name, msg)
if ok then
pending[name] = { sent_ms = ts, lat_e6 = lat6, lon_e6 = lon6 }
set_row_result(name, nil, nil, nil)
sys.toast("Ping → " .. name, 800)
else
sys.toast("Error: " .. tostring(err), 2000)
end
end



function app.on_message(m)
if m.kind ~= "dm" then return end
local text = tostring(m.text or "")


if text:sub(1, #PING_PFX) == PING_PFX then
local ts_s, _, _ = text:sub(#PING_PFX + 1):match("(-?%d+):(-?%d+):(-?%d+)")
if ts_s then
local fix = sys.gps()
local my6lat = fix and fix.lat_e6 or 0
local my6lon = fix and fix.lon_e6 or 0
mesh.send_dm(m.sender, string.format("%s%s:%d:%d", PONG_PFX, ts_s, my6lat, my6lon))
end
return
end


if text:sub(1, #PONG_PFX) == PONG_PFX then
local ts_s, their_lat_s, their_lon_s =
text:sub(#PONG_PFX + 1):match("(-?%d+):(-?%d+):(-?%d+)")
if not ts_s then return end

local sent_ms = tonumber(ts_s)
local rtt     = sys.millis() - sent_ms

local dist_m, cardinal
local p = pending[m.sender]
if p and geo and tonumber(their_lat_s) ~= 0 and p.lat_e6 ~= 0 then
local my_lat  = p.lat_e6        / 1000000.0
local my_lon  = p.lon_e6        / 1000000.0
local th_lat  = tonumber(their_lat_s) / 1000000.0
local th_lon  = tonumber(their_lon_s) / 1000000.0
dist_m  = geo.distance(my_lat, my_lon, th_lat, th_lon)
local brg = geo.bearing(my_lat, my_lon, th_lat, th_lon)
cardinal  = geo.cardinal(brg)
end

pending[m.sender] = nil
set_row_result(m.sender, rtt, dist_m, cardinal)

local notice = m.sender .. ": " .. rtt .. "ms"
if dist_m then notice = notice .. "  " .. dist_str(dist_m) end
sys.toast(notice, 2500)
return
end
end



function app.on_open(w, h)
W, H = w, h
ui.scroll(true)

local cy = 6
gps_lbl = ui.label(gps_line(), 6, cy, 11, C.sub)
gps_lbl:width(w - 12)
cy = cy + 20

local contacts = mesh.contacts()

if #contacts == 0 then
ui.label("No contacts visible", 8, cy, 12, C.sub)
timer.every(5000)
return
end

for _, ct in ipairs(contacts) do
local name = ct.name
local nl = ui.label(name, 8, cy, 13, C.text)
nl:width(w - 68)
local rl = ui.label("—", 8, cy + 16, 11, C.sub)
rl:width(w - 68)
local cap = name
ui.button("Ping", w - 60, cy + 4, 52, 28, function()
do_ping(cap)
end)
rows[#rows + 1] = { name = name, result_lbl = rl }
cy = cy + 44
end

timer.every(5000)
end

function app.on_tick(dt)
if gps_lbl then gps_lbl:set(gps_line()) end
end

function app.on_close() end

return app
)WADALUA";
#endif

static const LuaBuiltinApp kLuaBuiltin[] = {
  { "monitor", "RF Monitor", "1.3", kLuaSrc_monitor },
  { "airtime", "Airtime", "1.5", kLuaSrc_airtime },
  { "snake", "Snake", "1.0", kLuaSrc_snake },
#if CAP_LUA_SDK_EXT
  { "sdktest", "SDK Test", "1.7", kLuaSrc_sdktest },
#endif
#if CAP_LUA_SDK_EXT
  { "wardrive", "Wardrive", "1.2", kLuaSrc_wardrive },
#endif
#if CAP_LUA_SDK_EXT
  { "nearby", "Nearby", "1.0", kLuaSrc_nearby },
#endif
#if CAP_LUA_SDK_EXT
  { "ping", "Ping", "1.0", kLuaSrc_ping },
#endif
};
static const int kLuaBuiltinCount = (int)(sizeof(kLuaBuiltin)/sizeof(kLuaBuiltin[0]));
